version: '3'

services:
  backend:
    build: ./backend
    container_name: backend
    networks:
      - webnet

  frontend:
    build: ./frontend
    container_name: frontend
    networks:
      - webnet

  nginx:
    image: nginx:alpine
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./certs:/etc/nginx/certs
    depends_on:
      - backend
      - frontend
    networks:
      - webnet

networks:
  webnet:
